server:
  port: 9000
spring:
  data:
    mongodb:
      host: localhost             # MongoDB host (use 'localhost' for a local MongoDB instance)
      port: 27017                # MongoDB port
      database: PersistentCartDB